### ISSUE TITLE
Associate Accounts with Budgets

### ISSUE THREAD

**Issue by terenceponce** [obudget/core#8]
When a user logs in the app, they should only see what accounts they're associated with. They shouldn't see another person's accounts.

**Comment by richardneililagan** [comment]
Would you prefer this to be resourced through `/users/:id/accounts`, or just plain `/accounts` then constricted to the user auth claim? :p 

Based on how your work is going, it's looking like you prefer the latter?

**Comment by terenceponce** [comment]
Hi @richardneililagan! Yup, you're correct; It's the latter.

The idea that I have for this is to not associate Accounts and Users directly, but to associate Accounts to Budgets instead.

The reason I want it that way is because I want to implement multi-user support for Budgets. A user can have multiple budgets and a budget can be associated to a group of users as well.

So the idea is that Budgets are the entry point for most data and we're going to get the budget based on the current user's `active_budget` record (added in #31).

I already made some progress on this in [this branch](https://github.com/obudget/core/tree/budget-account-association), but you're welcome to finish the whole thing if you want. Just rebase the branch from master and you're good to go. I can also give you write access to this repo if you're going to push through with this.

**Comment by terenceponce** [comment]
I made a drawing of the structure that I had in mind here: https://github.com/obudget/core/issues/5#issuecomment-339897128

**Comment by richardneililagan** [comment]
Ah, understood.

I'm actually using this project as a sort of springboard into Elixir + Phoenix, so don't let me hold you up if you want this done already. I can always jump onto something else.

In hindsight, I might actually be of better help on the UI aspect of things, so I'll take a look at that as well.

**Comment by terenceponce** [comment]
Sure, no worries. I think you'd be a great help since I'm not much of a UI guy.
